# Created on: Feb 05, 2020
#     Author: Jose Tomas Lorente
# Configuration for subscribers to cmd_vel sources. This file is provided just as an example.
# Typically automatic controllers, as ROS navigation stack should have the minimum priority
#
# Used with example.launch
#
# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides cmd_vel messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT
#   short_desc:     Short description

cmd_vel_mux:
  ros__parameters:
    subscribers:
        default_input:
          topic:       "/mux/cmd_vel_rocos"
          timeout:     0.1
          priority:    0
          short_desc:  "The default cmd_vel is from rocos."
        navigation_stack:
          topic:       "/mux/cmd_vel_autonomous"
          timeout:     0.5
          priority:    1
          short_desc:  "Navigation stack controller"
        autodrive_stack:
          topic:       "/mux/cmd_vel_autodrive"
          timeout:     0.1
          priority:    10
          short_desc:  "Navigation stack remote control"
